<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_guidebar</name>
   <tag></tag>
   <elementGuidId>860323f8-ee3e-4f0c-842f-9b3bb3a8588d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-space</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41e79481-a96b-4a96-b93c-ffdca16310c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ce73eb36-2f74-4dc3-884a-48de9ae0206b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-space</value>
      <webElementGuid>42339c0a-403a-4c8e-82d3-54b6272d019a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>h</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>f61aa764-693b-4bb5-9f8d-3d34a7d449fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-w</name>
      <type>Main</type>
      <value>7xl</value>
      <webElementGuid>6df0a0db-7a2b-413e-be75-63d4d52a5030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>m</name>
      <type>Main</type>
      <value>x-auto</value>
      <webElementGuid>bc760c67-29f5-4d62-955e-823208a0a718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>p</name>
      <type>Main</type>
      <value>x-sm</value>
      <webElementGuid>80c3815d-ac3a-4f8a-9fea-6065b235a230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>45871687-a153-4827-bf92-b9c3b536818f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>師大資工線上申請系統首頁=身分ENadmin登出</value>
      <webElementGuid>aabab36b-011d-4cee-b9d5-ccbe6b2fb812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout-header n-layout-header--static-positioned n-layout-header--bordered&quot;]/div[@class=&quot;n-space&quot;]</value>
      <webElementGuid>28ce99d2-1820-42cd-8105-ef6d807af80e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div</value>
      <webElementGuid>03e5294e-034e-4ae2-bc04-35a5947ed06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>a4da89ad-29f1-4d61-a73e-d19ffc635ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '師大資工線上申請系統首頁=身分ENadmin登出' or . = '師大資工線上申請系統首頁=身分ENadmin登出')]</value>
      <webElementGuid>401d3bc1-ad0c-4b04-9077-692acb4d6ec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
