<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ID</name>
   <tag></tag>
   <elementGuidId>f2e28fda-ba96-44b7-810f-2304c9d9427e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-input.n-input--resizable.n-input--focus.n-input--stateful > div.n-input-wrapper > div.n-input__input > input.n-input__input-el</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84d189c2-e7fc-43ae-ae6f-435453a53da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>07186014-0782-4c60-b094-cb8337e5f7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-input__input-el</value>
      <webElementGuid>dc28c82b-5449-4988-adc6-38737efb5252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input</value>
      <webElementGuid>ccf33ce9-c2c9-431e-854b-18c95d07d783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>39a1a3b8-5506-4eef-a5fe-8ec652256adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;n-modal-container&quot;]/div[@class=&quot;n-modal-body-wrapper&quot;]/div[@class=&quot;n-scrollbar&quot;]/div[@class=&quot;n-scrollbar-container&quot;]/div[@class=&quot;n-scrollbar-content n-modal-scroll-content&quot;]/div[@class=&quot;n-card n-card--bordered n-modal&quot;]/div[@class=&quot;n-card__content&quot;]/form[@class=&quot;n-form&quot;]/div[@class=&quot;n-form-item __form-item-ml n-form-item--medium-size n-form-item--left-labelled n-form-item--auto-label-width&quot;]/div[@class=&quot;n-form-item-blank&quot;]/div[@class=&quot;n-input n-input--resizable n-input--focus n-input--stateful&quot;]/div[@class=&quot;n-input-wrapper&quot;]/div[@class=&quot;n-input__input&quot;]/input[@class=&quot;n-input__input-el&quot;]</value>
      <webElementGuid>5416d573-ab56-4b1c-b00a-7c77cca89019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[8]</value>
      <webElementGuid>b872075b-c0e5-42fc-94b9-c887e527c978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/input</value>
      <webElementGuid>cb81fc35-8d72-4a91-959a-994d914efbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Input']</value>
      <webElementGuid>5a3ecd04-7da9-4da0-b2fd-cd2962321727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
