<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_nowInCalender</name>
   <tag></tag>
   <elementGuidId>0a2bc660-ee90-43e9-9d5e-c04b32b4d052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.n-button.n-button--default-type.n-button--tiny-type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf585672-71d6-489e-8846-26cfa83c95be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-button n-button--default-type n-button--tiny-type</value>
      <webElementGuid>047342a3-2fda-4f97-abb3-05ad212f4d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>55bd6f34-5f18-4d13-a8ff-7e504ce5ad2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0fbc29a2-4b3f-4509-bcfd-aaf298ee9d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>此刻</value>
      <webElementGuid>fb353a60-b500-4217-ae87-31c65dd82677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;v-binder-follower-container&quot;]/div[@class=&quot;v-binder-follower-content&quot;]/div[@class=&quot;n-date-panel n-date-panel--date n-date-panel--shadow&quot;]/div[@class=&quot;n-date-panel-actions&quot;]/div[@class=&quot;n-date-panel-actions__suffix&quot;]/button[@class=&quot;n-button n-button--default-type n-button--tiny-type&quot;]</value>
      <webElementGuid>84e5a88f-3d2e-4ca6-9903-7bf90d28a5de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>2aeda882-4822-4a56-b14e-b933423d04b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='日'])[1]/following::button[1]</value>
      <webElementGuid>26b995b8-ed18-46f5-903f-798d2bc54185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='六'])[1]/following::button[1]</value>
      <webElementGuid>a57e0341-1c25-4ffe-947d-474f0f29a28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>6f40ae68-b30c-478c-a81d-61211fe7ef19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '此刻' or . = '此刻')]</value>
      <webElementGuid>9c98d930-eda9-482b-847c-da09649bb2f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
