<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_input_phonepls</name>
   <tag></tag>
   <elementGuidId>9b43aa43-374f-4adc-a1ad-cd0082ca1f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[2]/div/div/div/div/form/div/div[6]/div/div[2]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9a8a195-6d67-47cf-992a-13a2d25529c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-form-item-feedback__line</value>
      <webElementGuid>36a39b9c-bac4-4c93-aadc-eee24b512dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>請輸入手機</value>
      <webElementGuid>7048ff54-c739-4ff3-969d-ad6c02f770e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;justify-center pt-4 mx-auto md:w-2/3 max-w-11/12 lg:w-screen-md&quot;]/div[@class=&quot;n-card n-card--bordered&quot;]/div[@class=&quot;n-card__content&quot;]/form[@class=&quot;n-form&quot;]/div[@class=&quot;n-space&quot;]/div[6]/div[@class=&quot;n-space&quot;]/div[2]/div[@class=&quot;n-form-item __form-item-sl n-form-item--small-size n-form-item--left-labelled&quot;]/div[@class=&quot;n-form-item-feedback-wrapper&quot;]/div[@class=&quot;n-form-item-feedback n-form-item-feedback--error&quot;]/div[@class=&quot;n-form-item-feedback__line&quot;]</value>
      <webElementGuid>aa1f1e9e-2fc6-4c2f-b741-eb52127cd2d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div/div/div/div/form/div/div[6]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>7b9c6f90-6400-492b-a91b-40f17ac55ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='手機'])[1]/following::div[10]</value>
      <webElementGuid>ce5be56c-8a63-4570-bb9a-a4585f112bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='地址'])[1]/preceding::div[1]</value>
      <webElementGuid>c546fad2-80ad-40b8-9ca0-6436e34fb1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='請輸入手機']/parent::*</value>
      <webElementGuid>fe10c327-b4dd-4696-b5d9-41ef48e11a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>239ab1c3-000f-45af-b937-f7a2c1c07b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '請輸入手機' or . = '請輸入手機')]</value>
      <webElementGuid>9f804f5f-a5ef-4840-bcff-e2ea42bfb953</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
