<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_registerBox</name>
   <tag></tag>
   <elementGuidId>e180a03e-8714-4700-b738-02897c229061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-card__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd71a648-b497-4cd1-89a3-e765752bd0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-card__content</value>
      <webElementGuid>43473418-7bb8-4847-b918-097d1dd70ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>46d4c210-ef01-49f3-9b7c-c13a0ce8be50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>註冊電子信箱 * 密碼 * 密碼確認 * 姓名 * 生日 *電話 * 手機 * 地址 * 身分證字號 * 就讀學校 *註冊</value>
      <webElementGuid>3d6ae326-bcb4-4de9-aa79-b4c1419d1632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;justify-center pt-4 mx-auto md:w-2/3 max-w-11/12 lg:w-screen-md&quot;]/div[@class=&quot;n-card n-card--bordered&quot;]/div[@class=&quot;n-card__content&quot;]</value>
      <webElementGuid>935d71fa-63f8-437b-ae30-5a6f7ed71acd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>b0fcec76-af75-4ff4-a862-1131e8518327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='註冊'])[1]/following::div[8]</value>
      <webElementGuid>b9af51c7-0563-4c0e-8b36-b9fc2de2d076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='登入'])[1]/following::div[12]</value>
      <webElementGuid>3dfe0a5f-230d-4991-a76c-1ac8e9139a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>188b68c1-82a4-4244-b0ec-94076a0ec553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '註冊電子信箱 * 密碼 * 密碼確認 * 姓名 * 生日 *電話 * 手機 * 地址 * 身分證字號 * 就讀學校 *註冊' or . = '註冊電子信箱 * 密碼 * 密碼確認 * 姓名 * 生日 *電話 * 手機 * 地址 * 身分證字號 * 就讀學校 *註冊')]</value>
      <webElementGuid>d1bd4411-5345-47ac-a68f-fa27fb89c0b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
