<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_guidebar</name>
   <tag></tag>
   <elementGuidId>283cf4fc-37ed-4571-a17e-704781b793b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-space</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ad1af524-4af4-4c37-83f6-253f58aadbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9853381f-b79b-41c9-bb62-9d355cb3dc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-space</value>
      <webElementGuid>f1853541-d1cd-4f87-a86b-92a7de12823d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>h</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>bd432cdf-4ee9-47b6-8595-8a6778a2c689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-w</name>
      <type>Main</type>
      <value>7xl</value>
      <webElementGuid>890e3d41-cda1-4363-ac46-de2f2c0c6965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>m</name>
      <type>Main</type>
      <value>x-auto</value>
      <webElementGuid>f765f37d-2495-4cc3-b94f-727b32b59ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>p</name>
      <type>Main</type>
      <value>x-sm</value>
      <webElementGuid>cd7f158d-cba2-459b-a24e-a5e5a5b8ac01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>900d1898-e753-41a7-978e-1c21c705fcf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>師大資工線上申請系統=身分EN登入註冊</value>
      <webElementGuid>b1bf2fb7-a22e-4f63-afde-1268edce10c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout-header n-layout-header--static-positioned n-layout-header--bordered&quot;]/div[@class=&quot;n-space&quot;]</value>
      <webElementGuid>185f0216-a4d3-4281-ab5f-a0234270307e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div</value>
      <webElementGuid>488f809b-1e5d-4e82-9dc0-ab1c96cf3b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>e34f4263-7b4c-43d5-9484-b5d2f47c98ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '師大資工線上申請系統=身分EN登入註冊' or . = '師大資工線上申請系統=身分EN登入註冊')]</value>
      <webElementGuid>a51d413c-24e3-4ee9-97a7-af09289d20b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
