<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_sele1</name>
   <tag></tag>
   <elementGuidId>5868e371-6b84-422b-bcd3-c6e8853b5481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-base-select-option.n-base-select-option--pending.n-base-select-option--show-checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='註冊'])[3]/following::div[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>542840b5-d119-4582-b77e-b66bc87b77f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-base-select-option n-base-select-option--pending n-base-select-option--show-checkmark</value>
      <webElementGuid>13fd0ace-db15-4598-bdf7-3c24ccbcebe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>師範大學</value>
      <webElementGuid>e675f52e-0466-42aa-8f6c-41bd8e8fc017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;v-binder-follower-container&quot;]/div[@class=&quot;v-binder-follower-content&quot;]/div[@class=&quot;n-base-select-menu n-select-menu&quot;]/div[@class=&quot;n-scrollbar&quot;]/div[@class=&quot;n-virtual-list v-vl&quot;]/div[@class=&quot;v-vl-items&quot;]/div[@class=&quot;v-vl-visible-items&quot;]/div[@class=&quot;n-base-select-option n-base-select-option--pending n-base-select-option--show-checkmark&quot;]</value>
      <webElementGuid>ad9fae58-4cd6-4196-8641-4a9377588484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d0204f9-67eb-4c96-867b-d55ca2e264cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-base-select-option n-base-select-option--pending n-base-select-option--show-checkmark</value>
      <webElementGuid>d1f9195b-5704-4290-a84f-8e85b622442a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>師範大學</value>
      <webElementGuid>f29353a8-26b2-4b91-b893-4fc4f7929174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;v-binder-follower-container&quot;]/div[@class=&quot;v-binder-follower-content&quot;]/div[@class=&quot;n-base-select-menu n-select-menu&quot;]/div[@class=&quot;n-scrollbar&quot;]/div[@class=&quot;n-virtual-list v-vl&quot;]/div[@class=&quot;v-vl-items&quot;]/div[@class=&quot;v-vl-visible-items&quot;]/div[@class=&quot;n-base-select-option n-base-select-option--pending n-base-select-option--show-checkmark&quot;]</value>
      <webElementGuid>30faf86c-6b7e-4f1a-a7a0-e06e404e7ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='註冊'])[3]/following::div[11]</value>
      <webElementGuid>2dd5ac74-caa9-419a-9d9d-3898a677c1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='吃飯大學'])[1]/preceding::div[2]</value>
      <webElementGuid>8e7aa3d1-d9f7-4341-a1de-2240b9f88cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>121c7762-0d03-4d17-84b9-7359a4516de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '師範大學' or . = '師範大學')]</value>
      <webElementGuid>53f43357-1d9e-4d76-bbb6-876602fdcab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
