<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__email</name>
   <tag></tag>
   <elementGuidId>8c619732-3ea8-4bea-9586-64530af47f92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.n-input__input-el</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2318fd98-fc5f-401d-ab39-7db715ae6600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ce2c9d7-cb6c-40a9-88d7-c40b283334fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-input__input-el</value>
      <webElementGuid>965f3422-a206-44b7-808a-145b537c420d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>46eb321e-b8b2-4b76-8ea1-76fcf1ea89af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;justify-center pt-4 mx-auto md:w-2/3 max-w-11/12 lg:w-screen-md&quot;]/div[@class=&quot;n-card n-card--bordered&quot;]/div[@class=&quot;n-card__content&quot;]/form[@class=&quot;n-form&quot;]/div[@class=&quot;n-space&quot;]/div[1]/div[@class=&quot;n-form-item __form-item-sl n-form-item--small-size n-form-item--left-labelled&quot;]/div[@class=&quot;n-form-item-blank&quot;]/div[@class=&quot;n-input n-input--resizable n-input--focus n-input--stateful&quot;]/div[@class=&quot;n-input-wrapper&quot;]/div[@class=&quot;n-input__input&quot;]/input[@class=&quot;n-input__input-el&quot;]</value>
      <webElementGuid>9364b01f-6e23-4362-be92-022fb2268dcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>9af8416d-0738-4fec-9097-47e0415279b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div/div/div/div/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>9a1a762c-f635-4125-8e7f-508777e3a0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>85e70290-695e-46e8-9635-4ee0e7bab6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d535a567-d8f3-4f04-b774-266d1f862e1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
