<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ID</name>
   <tag></tag>
   <elementGuidId>969035dd-e536-4919-b8af-b805390580a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-input.n-input--resizable.n-input--focus.n-input--stateful > div.n-input-wrapper > div.n-input__input > input.n-input__input-el</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57544bc5-1476-46db-8a07-ac15c0f5a766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49df3673-f94d-49d9-a01f-b9c36fba9f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-input__input-el</value>
      <webElementGuid>61436a1b-7a7f-4e58-810a-799bae240015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1a1953b1-7124-4fc2-aa2d-48f951c85c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;justify-center pt-4 mx-auto md:w-2/3 max-w-11/12 lg:w-screen-md&quot;]/div[@class=&quot;n-card n-card--bordered&quot;]/div[@class=&quot;n-card__content&quot;]/form[@class=&quot;n-form&quot;]/div[@class=&quot;n-space&quot;]/div[8]/div[@class=&quot;n-form-item __form-item-sl n-form-item--small-size n-form-item--left-labelled&quot;]/div[@class=&quot;n-form-item-blank&quot;]/div[@class=&quot;n-input n-input--resizable n-input--focus n-input--stateful&quot;]/div[@class=&quot;n-input-wrapper&quot;]/div[@class=&quot;n-input__input&quot;]/input[@class=&quot;n-input__input-el&quot;]</value>
      <webElementGuid>c80b6420-5525-4e66-92c6-f89e92c7c7c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[7]</value>
      <webElementGuid>7f760e33-1210-44a5-9f16-7c77a33073ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div/div/div/div/form/div/div[8]/div/div/div/div/div/input</value>
      <webElementGuid>bc1c2c53-903a-4436-a3e2-4fe6efac83dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/input</value>
      <webElementGuid>8675d2bb-dfeb-446f-b000-07284f9d7bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>7bb5996c-3461-4577-b297-204ba9671283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
