<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__address</name>
   <tag></tag>
   <elementGuidId>3f4fdac6-064c-40ad-b383-b6fc184a434e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-input.n-input--resizable.n-input--focus.n-input--stateful > div.n-input-wrapper > div.n-input__input > input.n-input__input-el</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81c58050-78c0-4375-9996-96cf9e893b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1326fa9-b5b0-49a5-9e37-b7b482944c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-input__input-el</value>
      <webElementGuid>2621d18d-dd1e-4b7a-8ff5-68abc9860dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>280a1c59-b910-4d0c-a66f-4e906b032a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;justify-center pt-4 mx-auto md:w-2/3 max-w-11/12 lg:w-screen-md&quot;]/div[@class=&quot;n-card n-card--bordered&quot;]/div[@class=&quot;n-card__content&quot;]/form[@class=&quot;n-form&quot;]/div[@class=&quot;n-space&quot;]/div[7]/div[@class=&quot;n-form-item __form-item-sl n-form-item--small-size n-form-item--left-labelled&quot;]/div[@class=&quot;n-form-item-blank&quot;]/div[@class=&quot;n-input n-input--resizable n-input--focus n-input--stateful&quot;]/div[@class=&quot;n-input-wrapper&quot;]/div[@class=&quot;n-input__input&quot;]/input[@class=&quot;n-input__input-el&quot;]</value>
      <webElementGuid>fb5fddd4-8247-4602-a469-246185de7e72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>b18bef6c-5781-4ee9-ac47-cc7104039ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div/div/div/div/form/div/div[7]/div/div/div/div/div/input</value>
      <webElementGuid>bae57677-87f8-436a-8c25-79902ce8b4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/input</value>
      <webElementGuid>48fd66c2-f278-419b-96e5-1d2b6d65db05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>10827c72-02a5-4bc9-ab86-703bbb73c8f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
