<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_edit</name>
   <tag></tag>
   <elementGuidId>71a6e7e4-274d-48ac-b859-28c48bd5db0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.n-button.n-button--default-type.n-button--small-type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89d43ada-05b6-4765-88d9-87b371a060e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-button n-button--default-type n-button--small-type</value>
      <webElementGuid>d3d6aab0-e738-406b-835b-e62e13ea49a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3165987d-4643-43d0-ab1c-bc3783a7a515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fdebd7a5-58bd-451f-a195-5ba133a85264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>編輯</value>
      <webElementGuid>c779797b-26ae-4b11-88fe-31d004998254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;n-modal-container&quot;]/div[@class=&quot;n-modal-body-wrapper&quot;]/div[@class=&quot;n-scrollbar&quot;]/div[@class=&quot;n-scrollbar-container&quot;]/div[@class=&quot;n-scrollbar-content n-modal-scroll-content&quot;]/div[@class=&quot;n-card n-card--bordered n-modal&quot;]/div[@class=&quot;n-card__content&quot;]/div[@class=&quot;n-data-table n-data-table--bordered n-data-table--single-line&quot;]/div[@class=&quot;n-data-table-wrapper&quot;]/div[@class=&quot;n-data-table-base-table&quot;]/div[@class=&quot;n-data-table-base-table-body n-scrollbar&quot;]/div[@class=&quot;n-scrollbar-container&quot;]/div[@class=&quot;n-scrollbar-content&quot;]/table[@class=&quot;n-data-table-table&quot;]/tbody[@class=&quot;n-data-table-tbody&quot;]/tr[@class=&quot;n-data-table-tr&quot;]/td[@class=&quot;n-data-table-td n-data-table-td--last-col n-data-table-td--last-row&quot;]/button[@class=&quot;n-button n-button--default-type n-button--small-type&quot;]</value>
      <webElementGuid>17b6cb9e-a7d8-4bf4-a9e7-7afaf4508049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>b9160a9c-05ce-4f94-8815-51c117f3823a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wonderwall'])[1]/following::button[1]</value>
      <webElementGuid>c946460b-1351-4e9b-be1b-4fba1e28f45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='確認'])[1]/preceding::button[1]</value>
      <webElementGuid>d8b9d03d-740e-45df-b642-c2fabd255ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/button</value>
      <webElementGuid>c122c877-6169-4432-8b71-9ebe14644a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '編輯' or . = '編輯')]</value>
      <webElementGuid>4e4dd6ea-d417-4068-9c72-d9a5f12500cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
