<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_guidebar</name>
   <tag></tag>
   <elementGuidId>40b8877a-8546-45d1-8d19-e370d268b6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-space</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27d98208-d5be-4c4e-acad-5795c29dd35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9e14629e-b3ed-4745-a008-9714eb8afdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-space</value>
      <webElementGuid>2a760ff7-fe5e-4b2a-986f-b36a7b6cb5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>h</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>b859d102-18b6-4e25-a30c-8d4a34c9a5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-w</name>
      <type>Main</type>
      <value>7xl</value>
      <webElementGuid>fb3d5f70-6ded-4926-8ddc-89b8a5fd9c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>m</name>
      <type>Main</type>
      <value>x-auto</value>
      <webElementGuid>b2e62bc4-b9f6-49b0-b74a-9fcd807e6c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>p</name>
      <type>Main</type>
      <value>x-sm</value>
      <webElementGuid>a0d60ae3-b024-49b2-89c2-747e6c8e4b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>2f317f6b-aae1-4d61-b7e4-5314211c4f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>師大資工線上申請系統首頁=身分ENApplicant登出</value>
      <webElementGuid>c6cdd064-54af-4253-bac5-a0bc8c558672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout-header n-layout-header--static-positioned n-layout-header--bordered&quot;]/div[@class=&quot;n-space&quot;]</value>
      <webElementGuid>929c07a8-5892-40a9-9705-0e7bf3a29e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div</value>
      <webElementGuid>3493def6-3a94-439e-a623-db53e0230f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>74279df1-444e-4fae-aa63-c9bf39597239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '師大資工線上申請系統首頁=身分ENApplicant登出' or . = '師大資工線上申請系統首頁=身分ENApplicant登出')]</value>
      <webElementGuid>bd51bbb0-db3b-48dc-8677-682765eae3dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
