<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_guidebar</name>
   <tag></tag>
   <elementGuidId>bf279c0d-4646-4084-9ad7-97e0be4573e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-space</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e39c8dbe-911f-4183-9628-4c8f6835eee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7698dbe3-bbd8-4f11-848d-1c3512d79eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-space</value>
      <webElementGuid>9729331a-107f-46dd-86e8-92afdf9c7f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>h</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>fd97f687-f218-42c5-b8d3-0f156c4a0b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-w</name>
      <type>Main</type>
      <value>7xl</value>
      <webElementGuid>cb47a662-e22b-412a-8b35-a3f4de18f29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>m</name>
      <type>Main</type>
      <value>x-auto</value>
      <webElementGuid>4ab69558-c0c2-4db9-a470-d86fc7016cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>p</name>
      <type>Main</type>
      <value>x-sm</value>
      <webElementGuid>e66235e3-85aa-4be3-8e57-bf966db7f48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>0add2d16-495a-4da6-bb39-08753c469e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>師大資工線上申請系統首頁=身分ENReviewer登出</value>
      <webElementGuid>3fa9f702-c35c-4951-a486-66ad6fd7a1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout-header n-layout-header--static-positioned n-layout-header--bordered&quot;]/div[@class=&quot;n-space&quot;]</value>
      <webElementGuid>a0b07f8d-a214-479c-b150-eb2c88bf97bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div</value>
      <webElementGuid>dc6c2d51-b04e-4c16-b77c-a04bec017f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>9ad02199-562d-4451-a3e8-162af9c2327f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '師大資工線上申請系統首頁=身分ENReviewer登出' or . = '師大資工線上申請系統首頁=身分ENReviewer登出')]</value>
      <webElementGuid>923914bb-aff3-4633-abec-22b1d1fc0a1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
